### ISSUE TITLE
invalid rosdep key

### ISSUE THREAD

**Issue by dirk-thomas** [sevenbitbyte/ros_openlighting#1]
https://github.com/sevenbitbyte/ros_openlighting/blob/c0642825db0e04030d0df945cb87133efaaf857f/ola_ros/package.xml#L13

Please either change the dependency or contribute to the rosdep database to provide mappings to system packages.

**Comment by sevenbitbyte** [comment]
For qt5 I can add a mapping to the rosdep database. However I am also depending upon OLA(the open lighting architecture) which currently distributed via a PPA. How do I go about supporting a PPA?

**Comment by dirk-thomas** [comment]
The rosdep database does not support specifying PPAs.

**Comment by sevenbitbyte** [comment]
[A pull request on rosdistro has been created which adds basic qt5 support to rosdep](https://github.com/ros/rosdistro/pull/6452). The package.xml has been updated to reflect the newly mapped packages.
